### ISSUE TITLE
Offline Playback throws SourceError

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#40]
**Which sample is this report about?**
https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/OfflinePlayback
The sdk is not stable and the app is getting crashed.
Please kindly test before release.

**Describe the bug**
Not able to play offline content.

**To Reproduce**
1. Download the content
2. Pause the download
3. Resume the Download
4. Once download complete play the content in offline it wont play.

**Expected behavior**
In offline it should play

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Version:

**Comment by ravirajjak** [comment]
@dweinber @matamegger @jarhoax 
Please look into this.

**Comment by matamegger** [comment]
We have used your steps to reproduce this issue. Unfortunately, we couldn't notice any issue in this workflow.
Would you kindly provide us more information on your setup?
- Are you using your own stream? If so, please provide it to us.
- Have you altered the sample?
- Even though you say every device is impacted by the reported issue. Can you please provide us information on your testing device(s)?
(- Maybe a step to reproduce is missing, or not detailed enough?) 

If you don't want to share any of those data publicly, please connect to: support@bitmovin.com

**Comment by Prashantj007** [comment]
@matamegger **Thanks for replying.**

### **To Reproduce this issue please follow below steps:**

1.Click on download icon
2.downloading process
3.pause the downloading content
4.Resume the downloading content
5.Once download complete play the content in offline it wont play.

We are using following stream and we not changed any code in sample.
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

OS: Pie
Version: 9.0

**### Expected behavior**
In offline it should play

Please kindly check and let us know if you need anything from our side.

**Comment by matamegger** [comment]
Your described issue is not reproducable on our side. The workflow works on multiple devices and Android versions. However, we have corrected a potential issue, which however should disrupt your workflow already at step `1.`.

Could you please check out the newest version of the sample apps, and give us new feedback.
Thanks!

**Comment by Prashantj007** [comment]
@matamegger  Please check attached file to reproduce above issue.

https://vimeo.com/user96882347/review/327659748/3cc32b4b1d

Please let me know if you need from our side.
Thanks
Prashant Jadhav

**Comment by Prashantj007** [comment]
@matamegger  Please check attached link for reproduce above issue.

https://drive.google.com/open?id=1GNp0tsmlVRihGOaiKK8P6hETvdyGIBlu

Please let me know if you anything from our side.

Thanks
Prashant Jadhav

**Comment by Prashantj007** [comment]
Please check below link

https://drive.google.com/open?id=1GNp0tsmlVRihGOaiKK8P6hETvdyGIBlu

Thanks
Prashant

**Comment by ravirajjak** [comment]
@matamegger @dweinber @LudoMichaud @jarhoax 
We are using your latest sdk which is 2.20 and the issue still persist.
even in your sample there is a issue.
Please check the given link by @Prashantj007

**Comment by matamegger** [comment]
@ravirajjak 
FYI: The latest release is `2.22.0`.
`2.20` was release over a month ago.

**Comment by ravirajjak** [comment]
@matamegger even after updating the version to 2.22.0 its still not working.
I need your suggestion if its not SDK issue then what issue it could be?

**Comment by matamegger** [comment]
It was possible to reproduce the issue on our side! 🎉 
A potential fix will be included in an upcoming release of the SDK.

Thanks for reporting!

**Comment by ravirajjak** [comment]
@matamegger its a humble request you to solve it asap.
If our project delivery  gets delayed, we will be penalised. I hope you understand our situation!!

**Comment by akaita** [comment]
@matamegger in case it helps, this is the log with the latest code cloned from the `master` branch a few minutes ago 213050464b6773d2c0b430be9617595003d3cd80 
I just complied and run it in a 
- Pixel 
- Android 9
- 5 March 2019 security patch
- connected to a good wifi

I clicked to download the non-DRM version of `Art of Motion`, and I got this notification: https://www.4rtstudio.com/wb/bitmovin-offline-crash.png
A few seconds later the app crashed.

I put the whole log here, from the moment I opened the app to the moment it finally crashed: https://www.4rtstudio.com/wb/bitmovin-offline-crash.log

Same thing happens with any other stream I use.

**Comment by matamegger** [comment]
First of all the title is misleading, as the app was never crashing, just throwing an `ErrorEvent`.
Secondly, @akaita please don't forget to add a valid player license key.

For non sample related support requests please reach out to: support@bitmovin.com

**Comment by akaita** [comment]
@matamegger oh, my bad. Should have read the whole thing 🙇 . Will try again in a few

**Comment by matamegger** [comment]
@ravirajjak @Prashantj007 
A fix for this issue was released in `2.23.1`.

**Comment by Prashantj007** [comment]
Dear Matthias,

Thank you very much for resolving the issue. I really appreciate your
willingness to help.

It is helpful to have those who already experience the same issue.

Thanks & Regards

Prashant Jadhav

**Comment by ravirajjak** [comment]
@matamegger  thanks
